"""init

Revision ID: 510553f52617
Revises: 
Create Date: 2025-07-11 10:20:43.329843

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "510553f52617"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tokens",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("allegro_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_tokens_user_id"), "user_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "order_events",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("order_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["user_tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_events_event_type"), "order_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_order_events_occurred_at"),
        "order_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_events_order_id"), "order_events", ["order_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("token_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "allegro_order_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("order_data", sa.JSON(), nullable=True),
        sa.Column("order_date", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["user_tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_allegro_order_id"), "orders", ["allegro_order_id"], unique=False
    )
    op.create_index(
        op.f("ix_orders_order_date"), "orders", ["order_date"], unique=False
    )
    op.create_table(
        "sync_history",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("token_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("sync_started_at", sa.DateTime(), nullable=False),
        sa.Column("sync_completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "sync_status",
            sa.Enum("RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="syncstatus"),
            nullable=False,
        ),
        sa.Column("orders_processed", sa.Integer(), nullable=False),
        sa.Column("orders_added", sa.Integer(), nullable=False),
        sa.Column("orders_updated", sa.Integer(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sync_from_date", sa.DateTime(), nullable=True),
        sa.Column("sync_to_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["user_tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_history")
    op.drop_index(op.f("ix_orders_order_date"), table_name="orders")
    op.drop_index(op.f("ix_orders_allegro_order_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_index(op.f("ix_order_events_occurred_at"), table_name="order_events")
    op.drop_index(op.f("ix_order_events_event_type"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(op.f("ix_user_tokens_user_id"), table_name="user_tokens")
    op.drop_table("user_tokens")
    # ### end Alembic commands ###
