"""add_failed_order_processing_table

Revision ID: 856a6434a35b
Revises: 598a1eb13aa8
Create Date: 2025-07-30 15:24:47.970405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel import SQLModel
import sqlmodel


# revision identifiers, used by Alembic.
revision = "856a6434a35b"
down_revision = "598a1eb13aa8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_order_processing",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("order_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("token_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("error_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "error_details_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "action_required", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("event_data_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "expected_revision", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("first_failed_at", sa.DateTime(), nullable=False),
        sa.Column("last_retry_at", sa.DateTime(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_failed_order_processing_next_retry_at"),
        "failed_order_processing",
        ["next_retry_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_failed_order_processing_order_id"),
        "failed_order_processing",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_failed_order_processing_status"),
        "failed_order_processing",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_failed_order_processing_token_id"),
        "failed_order_processing",
        ["token_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_failed_order_processing_token_id"),
        table_name="failed_order_processing",
    )
    op.drop_index(
        op.f("ix_failed_order_processing_status"), table_name="failed_order_processing"
    )
    op.drop_index(
        op.f("ix_failed_order_processing_order_id"),
        table_name="failed_order_processing",
    )
    op.drop_index(
        op.f("ix_failed_order_processing_next_retry_at"),
        table_name="failed_order_processing",
    )
    op.drop_table("failed_order_processing")
    # ### end Alembic commands ###
