"""add_account_name_to_user_tokens

Revision ID: d34021e94765
Revises: 2ef0eff6b085
Create Date: 2025-07-18 06:49:09.488275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel import SQLModel
import sqlmodel


# revision identifiers, used by Alembic.
revision = "d34021e94765"
down_revision = "2ef0eff6b085"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_tokens",
        sa.Column("account_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_unique_constraint(
        "unique_user_account", "user_tokens", ["user_id", "account_name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_account", "user_tokens", type_="unique")
    op.drop_column("user_tokens", "account_name")
    # ### end Alembic commands ###
