"""fix constraint for user token

Revision ID: da65ca0007e5
Revises: f572f5c6df31
Create Date: 2025-07-30 10:38:20.118176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel import SQLModel
import sqlmodel


# revision identifiers, used by Alembic.
revision = "da65ca0007e5"
down_revision = "f572f5c6df31"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("unique_user_account"), "user_tokens", type_="unique")
    op.create_index(
        "unique_active_user_account",
        "user_tokens",
        ["user_id", "account_name"],
        unique=True,
        postgresql_where="is_active = true",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_active_user_account",
        table_name="user_tokens",
        postgresql_where="is_active = true",
    )
    op.create_unique_constraint(
        op.f("unique_user_account"),
        "user_tokens",
        ["user_id", "account_name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
