"""add active task schedules

Revision ID: dc671ff6cbd7
Revises: 74c7a32dc927
Create Date: 2025-07-14 12:37:34.288235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel import SQLModel
import sqlmodel


# revision identifiers, used by Alembic.
revision = "dc671ff6cbd7"
down_revision = "74c7a32dc927"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_sync_schedules",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("token_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("task_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_active_sync_schedules_task_name"),
        "active_sync_schedules",
        ["task_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_active_sync_schedules_token_id"),
        "active_sync_schedules",
        ["token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_active_sync_schedules_user_id"),
        "active_sync_schedules",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_active_sync_schedules_user_id"), table_name="active_sync_schedules"
    )
    op.drop_index(
        op.f("ix_active_sync_schedules_token_id"), table_name="active_sync_schedules"
    )
    op.drop_index(
        op.f("ix_active_sync_schedules_task_name"), table_name="active_sync_schedules"
    )
    op.drop_table("active_sync_schedules")
    # ### end Alembic commands ###
