"""order_technical flags

Revision ID: f572f5c6df31
Revises: d34021e94765
Create Date: 2025-07-25 13:31:27.832413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlmodel import SQLModel
import sqlmodel


# revision identifiers, used by Alembic.
revision = "f572f5c6df31"
down_revision = "d34021e94765"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_technical_flags",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("token_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "allegro_order_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_stock_updated", sa.Boolean(), nullable=False),
        sa.Column("has_invoice_created", sa.Boolean(), nullable=False),
        sa.Column("invoice_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["user_tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "token_id", "allegro_order_id", name="uq_order_technical_flags_per_order"
        ),
    )
    op.create_index(
        op.f("ix_order_technical_flags_allegro_order_id"),
        "order_technical_flags",
        ["allegro_order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_order_technical_flags_allegro_order_id"),
        table_name="order_technical_flags",
    )
    op.drop_table("order_technical_flags")
    # ### end Alembic commands ###
